version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:0.5.1-pg16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'app']
      interval: 10s
      retries: 5
  redis:
    image: redis:7
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      retries: 5
  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - APP_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=app
      - REDIS_HOST=redis
      - JWT_SECRET=changeme
      - LLM_PROVIDER=openai
      - LLM_API_KEY=changeme
      - VECTOR_DIM=1536
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8000:8000'
  worker:
    build: ./backend
    command: python -m app.workers.worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_started
    ports:
      - '3000:3000'
volumes:
  pgdata:
  redisdata:
